# Link prediction eval results

Decoder types are discovered automatically as subdirectories of `lp_eval/`
(currently `bilinear`, `hadamard`, ...) — adding a new decoder's output
directory is enough to pick it up, no code changes needed. Each directory
holds files named `dataset-partitions-iteration.out`.

For every discovered decoder the same report is generated: per-metric
`dataset x partitions` summary tables (`Hits@1`, `Hits@3`, `Hits@10`, `MRR`,
`F1`), the pooled Spearman correlation between `F1` and `MRR`, and
Mann-Whitney/Cohen's d significance of `MRR` across adjacent partition
counts.

`F1` is the graph-reconstruction F1 score (`Best achieved F1 score` line)
reported for that particular run's partitioning search — it is *not*
averaged across runs, it's a single per-run value like the other metrics.

A final section compares every pair of decoder types against each other,
at the `(dataset, partitions)` level, using the same Mann-Whitney/Cohen's d
machinery.

In [72]:
from __future__ import annotations

import itertools
import os
import re
from dataclasses import dataclass
from enum import Enum

import numpy as np
import pandas as pd
from scipy import stats

LP_EVAL_DIR = os.path.join("..", "lp_eval")
SIGNIFICANCE_LEVEL = 0.05
MIN_SAMPLES_FOR_TEST = 2


class Metric(str, Enum):
    HITS_1 = "Hits@1"
    HITS_3 = "Hits@3"
    HITS_10 = "Hits@10"
    MRR = "MRR"
    F1 = "F1"


ALL_METRICS: tuple[Metric, ...] = tuple(Metric)

METRIC_LINE_PATTERNS: dict[Metric, re.Pattern[str]] = {
    Metric.HITS_1: re.compile(r"Full Model - Hits@1:\s*([\d.]+)"),
    Metric.HITS_3: re.compile(r"Full Model - Hits@3:\s*([\d.]+)"),
    Metric.HITS_10: re.compile(r"Full Model - Hits@10:\s*([\d.]+)"),
    Metric.MRR: re.compile(r"Full Model - MRR:\s*([\d.]+)"),
    Metric.F1: re.compile(r"Best achieved F1 score:\s*([\d.]+)"),
}

# dataset names can themselves contain dashes (e.g. AS-Oregon, Cit-HepPh),
# so only the trailing `-partitions-iteration` is peeled off.
RUN_FILENAME_PATTERN = re.compile(
    r"^(?P<dataset>.+)-(?P<partitions>\d+)-(?P<iteration>\d+)\.out$"
)


def parse_metrics_from_log(log_text: str) -> dict[Metric, float | None]:
    metric_values: dict[Metric, float | None] = {}
    for metric, pattern in METRIC_LINE_PATTERNS.items():
        match = pattern.search(log_text)
        metric_values[metric] = (
            float(match.group(1)) if match else None
        )
    return metric_values

In [73]:
def discover_decoder_names(lp_eval_dir: str) -> list[str]:
    decoder_dirs = [
        entry.name for entry in os.scandir(lp_eval_dir) if entry.is_dir()
    ]
    return sorted(decoder_dirs)


def build_decoder_dataframe(directory: str, decoder: str) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for filename in sorted(os.listdir(directory)):
        match = RUN_FILENAME_PATTERN.match(filename)
        if match is None:
            continue
        else:
            file_path = os.path.join(directory, filename)
            with open(file_path, "r") as log_file:
                metric_values = parse_metrics_from_log(log_file.read())
            row = {
                "decoder": decoder,
                "dataset": match.group("dataset"),
                "partitions": int(match.group("partitions")),
                "iteration": int(match.group("iteration")),
            }
            row.update({m.value: v for m, v in metric_values.items()})
            rows.append(row)
    columns = ["decoder", "dataset", "partitions", "iteration"]
    columns += [metric.value for metric in ALL_METRICS]
    return pd.DataFrame(rows, columns=columns)


def load_all_decoder_results(lp_eval_dir: str) -> pd.DataFrame:
    decoder_frames = [
        build_decoder_dataframe(os.path.join(lp_eval_dir, decoder), decoder)
        for decoder in discover_decoder_names(lp_eval_dir)
    ]
    return pd.concat(decoder_frames, ignore_index=True)

In [74]:
all_results_df = load_all_decoder_results(LP_EVAL_DIR)
all_results_df

,decoder,dataset,partitions,iteration,Hits@1,Hits@3,Hits@10,MRR,F1
0,bilinear,AS-Oregon,1,0,0.156,0.290,0.447,0.2552,0.333738
1,bilinear,AS-Oregon,1,1,0.138,0.286,0.440,0.2390,0.337377
2,bilinear,AS-Oregon,1,2,0.154,0.275,0.446,0.2449,0.340755
3,bilinear,AS-Oregon,1,3,0.149,0.293,0.464,0.2503,0.338278
4,bilinear,AS-Oregon,1,4,0.151,0.280,0.449,0.2478,0.341372
...,...,...,...,...,...,...,...,...,...
475,random_forest,Cit-HepPh,8,5,0.351,0.542,0.726,0.4760,0.616557
476,random_forest,Cit-HepPh,8,6,0.358,0.542,0.719,0.4795,0.615350
477,random_forest,Cit-HepPh,8,7,0.349,0.516,0.711,0.4664,0.608906
478,random_forest,Cit-HepPh,8,8,0.330,0.508,0.699,0.4511,0.615448
479,random_forest,Cit-HepPh,8,9,0.368,0.542,0.730,0.4870,0.603988

In [75]:
def format_mean_and_stddev(mean: float, stddev: float) -> str:
    return f"{mean * 100:.2f}% \u00b1 {stddev * 100:.2f}%"


def build_metric_summary_table(
    df: pd.DataFrame, metric: Metric
) -> pd.DataFrame:
    grouped = df.groupby(["dataset", "partitions"])[metric.value]
    stats_df = grouped.agg(["mean", "std"])
    formatted = stats_df.apply(
        lambda row: format_mean_and_stddev(row["mean"], row["std"]),
        axis=1,
    )
    table = formatted.unstack("partitions")
    table.columns = [f"P={p}" for p in table.columns]
    return table

In [76]:
@dataclass
class GroupComparison:
    label_a: str
    label_b: str
    sample_size_a: int
    sample_size_b: int
    u_statistic: float
    p_value: float
    cohens_d: float

    @property
    def is_significant(self) -> bool:
        return self.p_value < SIGNIFICANCE_LEVEL


def compute_cohens_d(values_a: np.ndarray, values_b: np.ndarray) -> float:
    pooled_variance = (
        values_a.std(ddof=1) ** 2 + values_b.std(ddof=1) ** 2
    ) / 2
    pooled_stddev = np.sqrt(pooled_variance)
    if pooled_stddev == 0:
        return float("nan")
    else:
        return (values_b.mean() - values_a.mean()) / pooled_stddev


def compare_two_groups(
    label_a: str,
    values_a: np.ndarray,
    label_b: str,
    values_b: np.ndarray,
) -> GroupComparison | None:
    has_enough_samples = (
        len(values_a) >= MIN_SAMPLES_FOR_TEST
        and len(values_b) >= MIN_SAMPLES_FOR_TEST
    )
    if not has_enough_samples:
        return None
    else:
        u_statistic, p_value = stats.mannwhitneyu(
            values_a, values_b, alternative="two-sided"
        )
        return GroupComparison(
            label_a=label_a,
            label_b=label_b,
            sample_size_a=len(values_a),
            sample_size_b=len(values_b),
            u_statistic=u_statistic,
            p_value=p_value,
            cohens_d=compute_cohens_d(values_a, values_b),
        )

In [77]:
@dataclass(frozen=True)
class RunGroup:
    dataset: str
    partitions: int


def get_metric_values(
    df: pd.DataFrame, metric: Metric, decoder: str, group: RunGroup
) -> np.ndarray:
    mask = (
        (df["decoder"] == decoder)
        & (df["dataset"] == group.dataset)
        & (df["partitions"] == group.partitions)
    )
    return df.loc[mask, metric.value].to_numpy()


def get_partition_levels(df: pd.DataFrame) -> list[int]:
    return sorted(df["partitions"].unique())


def get_adjacent_pairs(levels: list[int]) -> list[tuple[int, int]]:
    return list(zip(levels, levels[1:]))


def compare_adjacent_partitions_for_dataset(
    df: pd.DataFrame,
    decoder: str,
    metric: Metric,
    dataset: str,
    adjacent_pairs: list[tuple[int, int]],
) -> list[GroupComparison]:
    comparisons = []
    for lower_partitions, higher_partitions in adjacent_pairs:
        values_a = get_metric_values(
            df, metric, decoder, RunGroup(dataset, lower_partitions)
        )
        values_b = get_metric_values(
            df, metric, decoder, RunGroup(dataset, higher_partitions)
        )
        comparison = compare_two_groups(
            f"P={lower_partitions}",
            values_a,
            f"P={higher_partitions}",
            values_b,
        )
        if comparison is None:
            continue
        else:
            comparisons.append(comparison)
    return comparisons


def group_comparison_to_row(
    dataset: str, comparison: GroupComparison
) -> dict[str, object]:
    return {
        "dataset": dataset,
        "comparison": f"{comparison.label_a} vs {comparison.label_b}",
        "n1": comparison.sample_size_a,
        "n2": comparison.sample_size_b,
        "U": comparison.u_statistic,
        "p-value": comparison.p_value,
        "Cohen's d": comparison.cohens_d,
        "significant": comparison.is_significant,
    }


def build_adjacent_partition_comparisons(
    df: pd.DataFrame, decoder: str, metric: Metric
) -> pd.DataFrame:
    adjacent_pairs = get_adjacent_pairs(get_partition_levels(df))
    datasets = sorted(
        df.loc[df["decoder"] == decoder, "dataset"].unique()
    )
    rows = [
        group_comparison_to_row(dataset, comparison)
        for dataset in datasets
        for comparison in compare_adjacent_partitions_for_dataset(
            df, decoder, metric, dataset, adjacent_pairs
        )
    ]
    return pd.DataFrame(rows)

In [78]:
def compute_pooled_spearman(
    df: pd.DataFrame, decoder: str, metric_a: Metric, metric_b: Metric
) -> tuple[float, float, int]:
    columns = [metric_a.value, metric_b.value]
    subset = df.loc[df["decoder"] == decoder, columns].dropna()
    correlation, p_value = stats.spearmanr(
        subset[metric_a.value], subset[metric_b.value]
    )
    return correlation, p_value, len(subset)


def print_decoder_header(decoder: str, run_count: int) -> None:
    print(f"## Decoder: {decoder} ({run_count} runs)")


def generate_decoder_report(df: pd.DataFrame, decoder: str) -> None:
    subset = df.loc[df["decoder"] == decoder]
    print_decoder_header(decoder, len(subset))
    for metric in ALL_METRICS:
        print(f"Metric: {metric.value}")
        display(build_metric_summary_table(subset, metric))
    correlation, p_value, sample_size = compute_pooled_spearman(
        df, decoder, Metric.F1, Metric.MRR
    )
    print(
        f"Spearman(F1, MRR): rho={correlation:.4f}, "
        f"p={p_value:.4g}, n={sample_size}"
    )
    print("MRR significance across adjacent partition counts:")
    display(
        build_adjacent_partition_comparisons(df, decoder, Metric.MRR)
    )

In [79]:
for decoder_name in discover_decoder_names(LP_EVAL_DIR):
    generate_decoder_report(all_results_df, decoder_name)

## Decoder: bilinear (160 runs)
Metric: Hits@1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  14.99% ± 1.07%   9.70% ± 1.23%   7.83% ± 1.13%   7.57% ± 1.40%
AstroPh    56.79% ± 1.58%  38.54% ± 1.70%  32.57% ± 2.29%  27.68% ± 2.34%
CITESEER   17.70% ± 1.14%  11.08% ± 1.79%   8.08% ± 0.99%   5.76% ± 1.10%
Cit-HepPh  48.38% ± 1.47%  31.05% ± 2.81%  27.10% ± 2.54%  24.90% ± 1.91%

Metric: Hits@3

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  29.22% ± 1.24%  21.21% ± 1.34%  17.64% ± 1.63%  16.60% ± 2.03%
AstroPh    77.48% ± 1.50%  58.30% ± 2.02%  51.70% ± 2.66%  44.71% ± 3.24%
CITESEER   32.25% ± 2.93%  19.69% ± 1.80%  15.54% ± 1.02%  12.01% ± 1.69%
Cit-HepPh  73.21% ± 1.82%  51.77% ± 4.09%  45.33% ± 4.16%  42.48% ± 2.77%

Metric: Hits@10

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  45.39% ± 1.44%  36.97% ± 1.19%  32.74% ± 3.00%  31.59% ± 2.28%
AstroPh    89.91% ± 0.78%  74.46% ± 1.37%  69.70% ± 1.91%  63.97% ± 2.55%
CITESEER   47.37% ± 3.50%  30.71% ± 2.55%  24.50% ± 1.34%  20.73% ± 1.73%
Cit-HepPh  89.85% ± 0.56%  72.40% ± 3.12%  64.52% ± 2.83%  60.36% ± 2.20%

Metric: MRR

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  25.08% ± 0.95%  18.69% ± 1.05%  15.96% ± 1.51%  15.34% ± 1.63%
AstroPh    68.74% ± 1.32%  51.03% ± 1.55%  45.19% ± 2.19%  39.64% ± 2.28%
CITESEER   27.61% ± 1.82%  17.90% ± 1.80%  13.80% ± 0.71%  10.94% ± 1.17%
Cit-HepPh  62.95% ± 1.13%  44.85% ± 3.05%  39.60% ± 2.81%  36.91% ± 2.02%

Metric: F1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  33.88% ± 0.28%  38.88% ± 1.91%  45.97% ± 3.79%  43.20% ± 1.78%
AstroPh    70.62% ± 0.08%  67.76% ± 0.09%  67.84% ± 0.12%  67.75% ± 0.11%
CITESEER   35.88% ± 1.46%  43.92% ± 3.25%  49.72% ± 2.34%  55.68% ± 6.12%
Cit-HepPh  54.87% ± 0.06%  57.41% ± 0.79%  60.35% ± 2.12%  61.59% ± 0.87%

Spearman(F1, MRR): rho=0.6189, p=2.719e-18, n=160
MRR significance across adjacent partition counts:

      dataset  comparison  n1  n2      U   p-value  Cohen's d  significant
0   AS-Oregon  P=1 vs P=2  10  10  100.0  0.000183  -6.366286         True
1   AS-Oregon  P=2 vs P=4  10  10   96.0  0.000583  -2.103067         True
2   AS-Oregon  P=4 vs P=8  10  10   61.0  0.427355  -0.394328        False
3     AstroPh  P=1 vs P=2  10  10  100.0  0.000183 -12.272210         True
4     AstroPh  P=2 vs P=4  10  10   99.0  0.000246  -3.067875         True
5     AstroPh  P=4 vs P=8  10  10   96.0  0.000583  -2.480379         True
6    CITESEER  P=1 vs P=2  10  10  100.0  0.000183  -5.354722         True
7    CITESEER  P=2 vs P=4  10  10   99.0  0.000246  -2.984246         True
8    CITESEER  P=4 vs P=8  10  10  100.0  0.000183  -2.964108         True
9   Cit-HepPh  P=1 vs P=2  10  10  100.0  0.000182  -7.863331         True
10  Cit-HepPh  P=2 vs P=4  10  10   89.0  0.003611  -1.789935         True
11  Cit-HepPh  P=4 vs P=8  10  10   81.0  0.021134  -1.099027         True

## Decoder: hadamard (160 runs)
Metric: Hits@1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon   6.99% ± 1.44%   4.92% ± 0.73%   4.08% ± 0.88%   4.49% ± 0.91%
AstroPh    20.73% ± 3.46%  16.93% ± 2.98%  18.53% ± 1.79%  19.56% ± 2.49%
CITESEER   14.37% ± 2.65%   8.21% ± 1.77%   7.64% ± 1.59%   9.38% ± 1.50%
Cit-HepPh  22.45% ± 2.49%  17.08% ± 1.24%  16.08% ± 1.42%  19.93% ± 1.69%

Metric: Hits@3

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  15.45% ± 2.20%  10.43% ± 1.09%   9.12% ± 1.22%  10.19% ± 1.17%
AstroPh    36.65% ± 4.97%  29.82% ± 3.68%  30.90% ± 1.76%  32.72% ± 2.94%
CITESEER   25.94% ± 3.57%  15.56% ± 2.43%  13.75% ± 1.36%  15.67% ± 1.49%
Cit-HepPh  43.07% ± 3.61%  32.01% ± 1.33%  30.70% ± 1.90%  37.74% ± 2.51%

Metric: Hits@10

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  29.62% ± 2.72%  21.46% ± 1.93%  18.50% ± 2.07%  20.43% ± 1.33%
AstroPh    55.58% ± 5.68%  46.86% ± 4.04%  47.57% ± 2.19%  49.85% ± 2.50%
CITESEER   38.96% ± 3.50%  24.46% ± 2.45%  21.52% ± 1.72%  21.39% ± 2.55%
Cit-HepPh  67.77% ± 3.84%  52.46% ± 1.58%  50.80% ± 1.67%  57.23% ± 2.52%

Metric: MRR

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  14.49% ± 1.68%  10.48% ± 0.78%   9.12% ± 1.08%   9.97% ± 0.86%
AstroPh    32.34% ± 4.13%  26.84% ± 3.22%  28.24% ± 1.63%  29.63% ± 2.50%
CITESEER   22.92% ± 2.80%  13.88% ± 1.88%  12.49% ± 1.37%  13.87% ± 1.66%
Cit-HepPh  37.05% ± 2.79%  28.38% ± 1.22%  27.15% ± 1.43%  32.15% ± 1.98%

Metric: F1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  34.19% ± 0.42%  39.12% ± 1.28%  46.01% ± 6.14%  45.10% ± 4.18%
AstroPh    70.59% ± 0.05%  67.85% ± 0.10%  67.81% ± 0.09%  67.79% ± 0.11%
CITESEER   36.20% ± 1.07%  43.41% ± 3.34%  50.71% ± 4.03%  55.04% ± 2.89%
Cit-HepPh  54.89% ± 0.08%  56.55% ± 0.52%  59.23% ± 2.37%  61.48% ± 0.90%

Spearman(F1, MRR): rho=0.6514, p=1.096e-20, n=160
MRR significance across adjacent partition counts:

      dataset  comparison  n1  n2      U   p-value  Cohen's d  significant
0   AS-Oregon  P=1 vs P=2  10  10   99.0  0.000246  -3.064031         True
1   AS-Oregon  P=2 vs P=4  10  10   89.0  0.003611  -1.432187         True
2   AS-Oregon  P=4 vs P=8  10  10   26.0  0.075662   0.864010        False
3     AstroPh  P=1 vs P=2  10  10   86.0  0.007285  -1.485964         True
4     AstroPh  P=2 vs P=4  10  10   34.5  0.256660   0.548755        False
5     AstroPh  P=4 vs P=8  10  10   32.0  0.185877   0.657899        False
6    CITESEER  P=1 vs P=2  10  10   98.5  0.000282  -3.790006         True
7    CITESEER  P=2 vs P=4  10  10   74.0  0.075552  -0.842243        False
8    CITESEER  P=4 vs P=8  10  10   20.0  0.025748   0.906642         True
9   Cit-HepPh  P=1 vs P=2  10  10  100.0  0.000183  -4.029513         True
10  Cit-HepPh  P=2 vs P=4  10  10   73.0  0.088973  -0.928916        False
11  Cit-HepPh  P=4 vs P=8  10  10    3.0  0.000440   2.896422         True

## Decoder: random_forest (160 runs)
Metric: Hits@1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  38.06% ± 1.60%  41.44% ± 1.77%  41.58% ± 1.75%  40.47% ± 1.08%
AstroPh    54.44% ± 1.42%  53.86% ± 1.85%  54.79% ± 1.53%  53.81% ± 1.38%
CITESEER   23.91% ± 1.43%  21.55% ± 1.96%  18.79% ± 1.72%  18.28% ± 1.61%
Cit-HepPh  40.31% ± 0.92%  37.57% ± 1.81%  35.82% ± 1.05%  35.31% ± 1.32%

Metric: Hits@3

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  44.35% ± 1.48%  47.14% ± 1.69%  46.99% ± 1.70%  46.25% ± 1.53%
AstroPh    66.61% ± 1.61%  66.12% ± 2.10%  66.49% ± 1.64%  65.79% ± 0.88%
CITESEER   35.70% ± 2.07%  30.40% ± 2.22%  26.91% ± 2.05%  26.14% ± 1.59%
Cit-HepPh  59.91% ± 1.30%  55.79% ± 1.55%  53.65% ± 1.59%  53.51% ± 1.42%

Metric: Hits@10

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  53.71% ± 1.27%  55.58% ± 1.82%  54.53% ± 1.55%  53.72% ± 1.45%
AstroPh    78.96% ± 1.45%  77.90% ± 2.41%  77.85% ± 1.23%  77.67% ± 0.97%
CITESEER   48.23% ± 2.61%  39.67% ± 2.87%  35.59% ± 2.35%  34.02% ± 2.01%
Cit-HepPh  79.78% ± 1.24%  74.61% ± 1.66%  72.98% ± 1.27%  72.38% ± 1.37%

Metric: MRR

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  43.26% ± 1.49%  46.25% ± 1.68%  46.09% ± 1.69%  45.13% ± 1.13%
AstroPh    62.73% ± 1.28%  62.05% ± 1.87%  62.70% ± 1.40%  61.95% ± 0.91%
CITESEER   32.27% ± 1.47%  28.02% ± 2.03%  24.75% ± 1.77%  23.99% ± 1.37%
Cit-HepPh  53.23% ± 0.97%  49.86% ± 1.59%  47.96% ± 0.75%  47.55% ± 1.08%

Metric: F1

                      P=1             P=2             P=4             P=8
dataset
AS-Oregon  34.03% ± 0.30%  38.92% ± 3.10%  44.79% ± 5.53%  44.88% ± 5.37%
AstroPh    70.58% ± 0.07%  67.86% ± 0.14%  67.83% ± 0.19%  67.76% ± 0.12%
CITESEER   36.11% ± 1.57%  42.33% ± 3.85%  49.48% ± 4.72%  55.77% ± 3.30%
Cit-HepPh  54.82% ± 0.08%  57.25% ± 0.76%  59.11% ± 1.94%  61.35% ± 0.73%

Spearman(F1, MRR): rho=0.7194, p=8.684e-27, n=160
MRR significance across adjacent partition counts:

      dataset  comparison  n1  n2     U   p-value  Cohen's d  significant
0   AS-Oregon  P=1 vs P=2  10  10  10.0  0.002827   1.879942         True
1   AS-Oregon  P=2 vs P=4  10  10  52.0  0.909722  -0.092914        False
2   AS-Oregon  P=4 vs P=8  10  10  67.0  0.212294  -0.669173        False
3     AstroPh  P=1 vs P=2  10  10  63.0  0.344704  -0.428529        False
4     AstroPh  P=2 vs P=4  10  10  39.0  0.427355   0.395589        False
5     AstroPh  P=4 vs P=8  10  10  66.0  0.241322  -0.637793        False
6    CITESEER  P=1 vs P=2  10  10  93.0  0.001315  -2.400018         True
7    CITESEER  P=2 vs P=4  10  10  95.0  0.000769  -1.716151         True
8    CITESEER  P=4 vs P=8  10  10  66.0  0.241322  -0.479937        False
9   Cit-HepPh  P=1 vs P=2  10  10  97.0  0.000440  -2.553117         True
10  Cit-HepPh  P=2 vs P=4  10  10  87.0  0.005795  -1.519381         True
11  Cit-HepPh  P=4 vs P=8  10  10  58.5  0.545199  -0.440272        False

# Decoder comparison

Every pair of decoder types is compared against each other metric by
metric, restricted to the `(dataset, partitions)` groups both decoders
have data for (so a decoder whose sweep hasn't finished yet only
contributes the groups it actually has runs for).

In [80]:
def get_common_groups(
    df: pd.DataFrame, decoder_a: str, decoder_b: str
) -> list[RunGroup]:
    key_columns = ["dataset", "partitions"]
    groups_a = df.loc[df["decoder"] == decoder_a, key_columns]
    groups_b = df.loc[df["decoder"] == decoder_b, key_columns]
    tuples_a = set(map(tuple, groups_a.values))
    tuples_b = set(map(tuple, groups_b.values))
    common_tuples = sorted(tuples_a & tuples_b)
    return [
        RunGroup(dataset=dataset, partitions=int(partitions))
        for dataset, partitions in common_tuples
    ]


def compare_decoders_for_group(
    df: pd.DataFrame,
    decoder_a: str,
    decoder_b: str,
    metric: Metric,
    group: RunGroup,
) -> GroupComparison | None:
    values_a = get_metric_values(df, metric, decoder_a, group)
    values_b = get_metric_values(df, metric, decoder_b, group)
    return compare_two_groups(decoder_a, values_a, decoder_b, values_b)


def decoder_comparison_to_row(
    group: RunGroup, comparison: GroupComparison
) -> dict[str, object]:
    return {
        "dataset": group.dataset,
        "partitions": group.partitions,
        "comparison": f"{comparison.label_a} vs {comparison.label_b}",
        "n1": comparison.sample_size_a,
        "n2": comparison.sample_size_b,
        "U": comparison.u_statistic,
        "p-value": comparison.p_value,
        "Cohen's d": comparison.cohens_d,
        "significant": comparison.is_significant,
    }


def build_decoder_comparison_table(
    df: pd.DataFrame, decoder_a: str, decoder_b: str, metric: Metric
) -> pd.DataFrame:
    common_groups = get_common_groups(df, decoder_a, decoder_b)
    comparisons = (
        (
            group,
            compare_decoders_for_group(
                df, decoder_a, decoder_b, metric, group
            ),
        )
        for group in common_groups
    )
    rows = [
        decoder_comparison_to_row(group, comparison)
        for group, comparison in comparisons
        if comparison is not None
    ]
    return pd.DataFrame(rows)

In [81]:
def print_decoder_pair_header(decoder_a: str, decoder_b: str) -> None:
    print(f"## {decoder_a} vs {decoder_b}")


def generate_decoder_comparison_report(
    df: pd.DataFrame, decoder_a: str, decoder_b: str
) -> None:
    print_decoder_pair_header(decoder_a, decoder_b)
    for metric in ALL_METRICS:
        table = build_decoder_comparison_table(
            df, decoder_a, decoder_b, metric
        )
        has_common_groups = not table.empty
        if not has_common_groups:
            print(f"{metric.value}: no overlapping groups yet")
            continue
        else:
            print(f"Metric: {metric.value}")
            display(table)

In [82]:
decoder_names = discover_decoder_names(LP_EVAL_DIR)
for decoder_a, decoder_b in itertools.combinations(decoder_names, 2):
    generate_decoder_comparison_report(all_results_df, decoder_a, decoder_b)

## bilinear vs hadamard
Metric: Hits@1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs hadamard,10,10,100.0,0.000183,-6.302926,True
1,AS-Oregon,2,bilinear vs hadamard,10,10,100.0,0.000181,-4.715473,True
2,AS-Oregon,4,bilinear vs hadamard,10,10,100.0,0.000177,-3.695284,True
3,AS-Oregon,8,bilinear vs hadamard,10,10,99.0,0.000238,-2.612944,True
4,AstroPh,1,bilinear vs hadamard,10,10,100.0,0.000182,-13.407253,True
5,AstroPh,2,bilinear vs hadamard,10,10,100.0,0.000181,-8.901517,True
6,AstroPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-6.840782,True
7,AstroPh,8,bilinear vs hadamard,10,10,100.0,0.000183,-3.355932,True
8,CITESEER,1,bilinear vs hadamard,10,10,88.0,0.004420,-1.634641,True
9,CITESEER,2,bilinear vs hadamard,10,10,88.5,0.004030,-1.614131,True
10,CITESEER,4,bilinear vs hadamard,10,10,60.0,0.471841,-0.335618,False
11,CITESEER,8,bilinear vs hadamard,10,10,1.0,0.000237,2.754836,True
12,Cit-HepPh,1,bilinear vs hadamard,10,10,100.0,0.000181,-12.687753,True
13,Cit-HepPh,2,bilinear vs hadamard,10,10,100.0,0.000183,-6.437758,True
14,Cit-HepPh,4,bilinear vs hadamard,10,10,100.0,0.000180,-5.352627,True
15,Cit-HepPh,8,bilinear vs hadamard,10,10,98.0,0.000328,-2.749795,True

Metric: Hits@3

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs hadamard,10,10,100.0,0.000183,-7.706969,True
1,AS-Oregon,2,bilinear vs hadamard,10,10,100.0,0.000182,-8.836263,True
2,AS-Oregon,4,bilinear vs hadamard,10,10,100.0,0.000182,-5.926583,True
3,AS-Oregon,8,bilinear vs hadamard,10,10,100.0,0.000181,-3.867368,True
4,AstroPh,1,bilinear vs hadamard,10,10,100.0,0.000182,-11.116156,True
5,AstroPh,2,bilinear vs hadamard,10,10,100.0,0.000182,-9.581390,True
6,AstroPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-9.229517,True
7,AstroPh,8,bilinear vs hadamard,10,10,100.0,0.000183,-3.878012,True
8,CITESEER,1,bilinear vs hadamard,10,10,94.0,0.000999,-1.931258,True
9,CITESEER,2,bilinear vs hadamard,10,10,92.5,0.001474,-1.926991,True
10,CITESEER,4,bilinear vs hadamard,10,10,84.0,0.011024,-1.487089,True
11,CITESEER,8,bilinear vs hadamard,10,10,3.5,0.000502,2.299054,True
12,Cit-HepPh,1,bilinear vs hadamard,10,10,100.0,0.000182,-10.539278,True
13,Cit-HepPh,2,bilinear vs hadamard,10,10,100.0,0.000182,-6.503496,True
14,Cit-HepPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-4.524249,True
15,Cit-HepPh,8,bilinear vs hadamard,10,10,91.0,0.002202,-1.793260,True

Metric: Hits@10

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs hadamard,10,10,100.0,0.000181,-7.235561,True
1,AS-Oregon,2,bilinear vs hadamard,10,10,100.0,0.000181,-9.686920,True
2,AS-Oregon,4,bilinear vs hadamard,10,10,100.0,0.000180,-5.527487,True
3,AS-Oregon,8,bilinear vs hadamard,10,10,100.0,0.000178,-5.976190,True
4,AstroPh,1,bilinear vs hadamard,10,10,100.0,0.000182,-8.471094,True
5,AstroPh,2,bilinear vs hadamard,10,10,100.0,0.000179,-9.156357,True
6,AstroPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-10.748616,True
7,AstroPh,8,bilinear vs hadamard,10,10,100.0,0.000183,-5.581759,True
8,CITESEER,1,bilinear vs hadamard,10,10,97.5,0.000375,-2.402573,True
9,CITESEER,2,bilinear vs hadamard,10,10,98.0,0.000321,-2.499396,True
10,CITESEER,4,bilinear vs hadamard,10,10,92.0,0.001672,-1.932024,True
11,CITESEER,8,bilinear vs hadamard,10,10,42.0,0.567529,0.303580,False
12,Cit-HepPh,1,bilinear vs hadamard,10,10,100.0,0.000181,-8.043848,True
13,Cit-HepPh,2,bilinear vs hadamard,10,10,100.0,0.000183,-8.071853,True
14,Cit-HepPh,4,bilinear vs hadamard,10,10,100.0,0.000178,-5.905485,True
15,Cit-HepPh,8,bilinear vs hadamard,10,10,83.0,0.013947,-1.324211,True

Metric: MRR

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs hadamard,10,10,100.0,0.000183,-7.771675,True
1,AS-Oregon,2,bilinear vs hadamard,10,10,100.0,0.000183,-8.860861,True
2,AS-Oregon,4,bilinear vs hadamard,10,10,100.0,0.000183,-5.207916,True
3,AS-Oregon,8,bilinear vs hadamard,10,10,100.0,0.000183,-4.116816,True
4,AstroPh,1,bilinear vs hadamard,10,10,100.0,0.000183,-11.874912,True
5,AstroPh,2,bilinear vs hadamard,10,10,100.0,0.000183,-9.568215,True
6,AstroPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-8.764870,True
7,AstroPh,8,bilinear vs hadamard,10,10,100.0,0.000183,-4.180661,True
8,CITESEER,1,bilinear vs hadamard,10,10,97.0,0.000440,-1.987049,True
9,CITESEER,2,bilinear vs hadamard,10,10,97.0,0.000437,-2.179813,True
10,CITESEER,4,bilinear vs hadamard,10,10,75.0,0.064022,-1.203931,False
11,CITESEER,8,bilinear vs hadamard,10,10,5.0,0.000769,2.045269,True
12,Cit-HepPh,1,bilinear vs hadamard,10,10,100.0,0.000182,-12.172734,True
13,Cit-HepPh,2,bilinear vs hadamard,10,10,100.0,0.000183,-7.084509,True
14,Cit-HepPh,4,bilinear vs hadamard,10,10,100.0,0.000183,-5.589841,True
15,Cit-HepPh,8,bilinear vs hadamard,10,10,95.5,0.000667,-2.384427,True

Metric: F1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs hadamard,10,10,22.0,0.037635,0.878550,True
1,AS-Oregon,2,bilinear vs hadamard,10,10,46.0,0.791337,0.144428,False
2,AS-Oregon,4,bilinear vs hadamard,10,10,43.0,0.623176,0.008905,False
3,AS-Oregon,8,bilinear vs hadamard,10,10,37.0,0.344704,0.590921,False
4,AstroPh,1,bilinear vs hadamard,10,10,70.0,0.140465,-0.408099,False
5,AstroPh,2,bilinear vs hadamard,10,10,29.0,0.121225,0.931371,False
6,AstroPh,4,bilinear vs hadamard,10,10,58.0,0.570750,-0.199289,False
7,AstroPh,8,bilinear vs hadamard,10,10,40.0,0.472676,0.293908,False
8,CITESEER,1,bilinear vs hadamard,10,10,46.0,0.791337,0.250220,False
9,CITESEER,2,bilinear vs hadamard,10,10,48.0,0.909722,-0.155608,False
10,CITESEER,4,bilinear vs hadamard,10,10,47.0,0.850107,0.301721,False
11,CITESEER,8,bilinear vs hadamard,10,10,60.0,0.472676,-0.133953,False
12,Cit-HepPh,1,bilinear vs hadamard,10,10,48.0,0.909722,0.173197,False
13,Cit-HepPh,2,bilinear vs hadamard,10,10,82.0,0.017257,-1.288016,True
14,Cit-HepPh,4,bilinear vs hadamard,10,10,68.0,0.185877,-0.495265,False
15,Cit-HepPh,8,bilinear vs hadamard,10,10,58.0,0.570750,-0.127886,False

## bilinear vs random_forest
Metric: Hits@1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs random_forest,10,10,0.0,0.000183,16.942841,True
1,AS-Oregon,2,bilinear vs random_forest,10,10,0.0,0.000181,20.772773,True
2,AS-Oregon,4,bilinear vs random_forest,10,10,0.0,0.000177,22.876756,True
3,AS-Oregon,8,bilinear vs random_forest,10,10,0.0,0.000178,26.312049,True
4,AstroPh,1,bilinear vs random_forest,10,10,85.5,0.008079,-1.566029,True
5,AstroPh,2,bilinear vs random_forest,10,10,0.0,0.000183,8.626671,True
6,AstroPh,4,bilinear vs random_forest,10,10,0.0,0.000182,11.421184,True
7,AstroPh,8,bilinear vs random_forest,10,10,0.0,0.000182,13.587911,True
8,CITESEER,1,bilinear vs random_forest,10,10,0.0,0.000178,4.780926,True
9,CITESEER,2,bilinear vs random_forest,10,10,0.0,0.000181,5.574848,True
10,CITESEER,4,bilinear vs random_forest,10,10,0.0,0.000180,7.627357,True
11,CITESEER,8,bilinear vs random_forest,10,10,0.0,0.000177,9.088073,True
12,Cit-HepPh,1,bilinear vs random_forest,10,10,100.0,0.000181,-6.600750,True
13,Cit-HepPh,2,bilinear vs random_forest,10,10,0.0,0.000183,2.761979,True
14,Cit-HepPh,4,bilinear vs random_forest,10,10,0.0,0.000181,4.489838,True
15,Cit-HepPh,8,bilinear vs random_forest,10,10,0.0,0.000181,6.333435,True

Metric: Hits@3

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs random_forest,10,10,0.0,0.000182,11.087068,True
1,AS-Oregon,2,bilinear vs random_forest,10,10,0.0,0.000183,17.004954,True
2,AS-Oregon,4,bilinear vs random_forest,10,10,0.0,0.000183,17.628873,True
3,AS-Oregon,8,bilinear vs random_forest,10,10,0.0,0.000182,16.463050,True
4,AstroPh,1,bilinear vs random_forest,10,10,100.0,0.000183,-6.971116,True
5,AstroPh,2,bilinear vs random_forest,10,10,0.0,0.000181,3.795838,True
6,AstroPh,4,bilinear vs random_forest,10,10,0.0,0.000181,6.690968,True
7,AstroPh,8,bilinear vs random_forest,10,10,0.0,0.000181,8.880744,True
8,CITESEER,1,bilinear vs random_forest,10,10,17.0,0.013768,1.356085,True
9,CITESEER,2,bilinear vs random_forest,10,10,0.0,0.000180,5.286399,True
10,CITESEER,4,bilinear vs random_forest,10,10,0.0,0.000179,7.019351,True
11,CITESEER,8,bilinear vs random_forest,10,10,0.0,0.000181,8.609472,True
12,Cit-HepPh,1,bilinear vs random_forest,10,10,100.0,0.000181,-8.400652,True
13,Cit-HepPh,2,bilinear vs random_forest,10,10,19.5,0.023290,1.300652,True
14,Cit-HepPh,4,bilinear vs random_forest,10,10,0.0,0.000183,2.643928,True
15,Cit-HepPh,8,bilinear vs random_forest,10,10,0.0,0.000179,5.013492,True

Metric: Hits@10

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs random_forest,10,10,0.0,0.000180,6.119007,True
1,AS-Oregon,2,bilinear vs random_forest,10,10,0.0,0.000182,12.103114,True
2,AS-Oregon,4,bilinear vs random_forest,10,10,0.0,0.000181,9.133729,True
3,AS-Oregon,8,bilinear vs random_forest,10,10,0.0,0.000182,11.577646,True
4,AstroPh,1,bilinear vs random_forest,10,10,100.0,0.000182,-9.429500,True
5,AstroPh,2,bilinear vs random_forest,10,10,13.0,0.005704,1.753136,True
6,AstroPh,4,bilinear vs random_forest,10,10,0.0,0.000181,5.066066,True
7,AstroPh,8,bilinear vs random_forest,10,10,0.0,0.000183,7.093485,True
8,CITESEER,1,bilinear vs random_forest,10,10,38.5,0.404617,0.279832,False
9,CITESEER,2,bilinear vs random_forest,10,10,0.0,0.000178,3.306278,True
10,CITESEER,4,bilinear vs random_forest,10,10,0.0,0.000180,5.796026,True
11,CITESEER,8,bilinear vs random_forest,10,10,0.0,0.000172,7.088909,True
12,Cit-HepPh,1,bilinear vs random_forest,10,10,100.0,0.000180,-10.492050,True
13,Cit-HepPh,2,bilinear vs random_forest,10,10,30.0,0.140017,0.885856,False
14,Cit-HepPh,4,bilinear vs random_forest,10,10,0.0,0.000182,3.857161,True
15,Cit-HepPh,8,bilinear vs random_forest,10,10,0.0,0.000181,6.562876,True

Metric: MRR

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs random_forest,10,10,0.0,0.000183,14.523680,True
1,AS-Oregon,2,bilinear vs random_forest,10,10,0.0,0.000183,19.627123,True
2,AS-Oregon,4,bilinear vs random_forest,10,10,0.0,0.000183,18.776186,True
3,AS-Oregon,8,bilinear vs random_forest,10,10,0.0,0.000183,21.244332,True
4,AstroPh,1,bilinear vs random_forest,10,10,100.0,0.000183,-4.621652,True
5,AstroPh,2,bilinear vs random_forest,10,10,0.0,0.000183,6.418054,True
6,AstroPh,4,bilinear vs random_forest,10,10,0.0,0.000183,9.518127,True
7,AstroPh,8,bilinear vs random_forest,10,10,0.0,0.000183,12.827452,True
8,CITESEER,1,bilinear vs random_forest,10,10,2.0,0.000330,2.810954,True
9,CITESEER,2,bilinear vs random_forest,10,10,0.0,0.000183,5.277414,True
10,CITESEER,4,bilinear vs random_forest,10,10,0.0,0.000183,8.105245,True
11,CITESEER,8,bilinear vs random_forest,10,10,0.0,0.000183,10.263548,True
12,Cit-HepPh,1,bilinear vs random_forest,10,10,100.0,0.000182,-9.241216,True
13,Cit-HepPh,2,bilinear vs random_forest,10,10,5.0,0.000769,2.055804,True
14,Cit-HepPh,4,bilinear vs random_forest,10,10,0.0,0.000183,4.066862,True
15,Cit-HepPh,8,bilinear vs random_forest,10,10,0.0,0.000183,6.573713,True

Metric: F1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,bilinear vs random_forest,10,10,36.0,0.307489,0.522937,False
1,AS-Oregon,2,bilinear vs random_forest,10,10,52.0,0.909722,0.015822,False
2,AS-Oregon,4,bilinear vs random_forest,10,10,56.0,0.677585,-0.247987,False
3,AS-Oregon,8,bilinear vs random_forest,10,10,47.0,0.850107,0.421259,False
4,AstroPh,1,bilinear vs random_forest,10,10,67.0,0.212294,-0.525332,False
5,AstroPh,2,bilinear vs random_forest,10,10,26.0,0.075662,0.869610,False
6,AstroPh,4,bilinear vs random_forest,10,10,50.0,1.000000,-0.037078,False
7,AstroPh,8,bilinear vs random_forest,10,10,45.0,0.733730,0.059936,False
8,CITESEER,1,bilinear vs random_forest,10,10,47.0,0.850107,0.146693,False
9,CITESEER,2,bilinear vs random_forest,10,10,72.0,0.104110,-0.444904,False
10,CITESEER,4,bilinear vs random_forest,10,10,51.0,0.969850,-0.063778,False
11,CITESEER,8,bilinear vs random_forest,10,10,56.0,0.677585,0.019196,False
12,Cit-HepPh,1,bilinear vs random_forest,10,10,72.0,0.104110,-0.787584,False
13,Cit-HepPh,2,bilinear vs random_forest,10,10,53.0,0.850107,-0.203753,False
14,Cit-HepPh,4,bilinear vs random_forest,10,10,68.0,0.185877,-0.609639,False
15,Cit-HepPh,8,bilinear vs random_forest,10,10,61.0,0.427355,-0.302542,False

## hadamard vs random_forest
Metric: Hits@1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,hadamard vs random_forest,10,10,0.0,0.000183,20.380649,True
1,AS-Oregon,2,hadamard vs random_forest,10,10,0.0,0.000181,26.906658,True
2,AS-Oregon,4,hadamard vs random_forest,10,10,0.0,0.000181,27.050773,True
3,AS-Oregon,8,hadamard vs random_forest,10,10,0.0,0.000180,36.030077,True
4,AstroPh,1,hadamard vs random_forest,10,10,0.0,0.000182,12.749026,True
5,AstroPh,2,hadamard vs random_forest,10,10,0.0,0.000181,14.879186,True
6,AstroPh,4,hadamard vs random_forest,10,10,0.0,0.000182,21.766886,True
7,AstroPh,8,hadamard vs random_forest,10,10,0.0,0.000182,16.980224,True
8,CITESEER,1,hadamard vs random_forest,10,10,0.0,0.000182,4.478781,True
9,CITESEER,2,hadamard vs random_forest,10,10,0.0,0.000179,7.144230,True
10,CITESEER,4,hadamard vs random_forest,10,10,0.0,0.000181,6.745096,True
11,CITESEER,8,hadamard vs random_forest,10,10,0.0,0.000178,5.724661,True
12,Cit-HepPh,1,hadamard vs random_forest,10,10,0.0,0.000181,9.518360,True
13,Cit-HepPh,2,hadamard vs random_forest,10,10,0.0,0.000183,13.205316,True
14,Cit-HepPh,4,hadamard vs random_forest,10,10,0.0,0.000180,15.806901,True
15,Cit-HepPh,8,hadamard vs random_forest,10,10,0.0,0.000182,10.132709,True

Metric: Hits@3

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,hadamard vs random_forest,10,10,0.0,0.000182,15.414704,True
1,AS-Oregon,2,hadamard vs random_forest,10,10,0.0,0.000182,25.848623,True
2,AS-Oregon,4,hadamard vs random_forest,10,10,0.0,0.000182,25.595045,True
3,AS-Oregon,8,hadamard vs random_forest,10,10,0.0,0.000180,26.474499,True
4,AstroPh,1,hadamard vs random_forest,10,10,0.0,0.000182,8.103976,True
5,AstroPh,2,hadamard vs random_forest,10,10,0.0,0.000182,12.110770,True
6,AstroPh,4,hadamard vs random_forest,10,10,0.0,0.000181,20.937508,True
7,AstroPh,8,hadamard vs random_forest,10,10,0.0,0.000181,15.262625,True
8,CITESEER,1,hadamard vs random_forest,10,10,0.0,0.000181,3.338915,True
9,CITESEER,2,hadamard vs random_forest,10,10,0.0,0.000179,6.361982,True
10,CITESEER,4,hadamard vs random_forest,10,10,0.0,0.000180,7.560631,True
11,CITESEER,8,hadamard vs random_forest,10,10,0.0,0.000182,6.811707,True
12,Cit-HepPh,1,hadamard vs random_forest,10,10,0.0,0.000182,6.202860,True
13,Cit-HepPh,2,hadamard vs random_forest,10,10,0.0,0.000182,16.445036,True
14,Cit-HepPh,4,hadamard vs random_forest,10,10,0.0,0.000183,13.102407,True
15,Cit-HepPh,8,hadamard vs random_forest,10,10,0.0,0.000179,7.735340,True

Metric: Hits@10

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,hadamard vs random_forest,10,10,0.0,0.000180,11.327851,True
1,AS-Oregon,2,hadamard vs random_forest,10,10,0.0,0.000182,18.188892,True
2,AS-Oregon,4,hadamard vs random_forest,10,10,0.0,0.000182,19.665571,True
3,AS-Oregon,8,hadamard vs random_forest,10,10,0.0,0.000177,23.956805,True
4,AstroPh,1,hadamard vs random_forest,10,10,0.0,0.000183,5.642159,True
5,AstroPh,2,hadamard vs random_forest,10,10,0.0,0.000182,9.337151,True
6,AstroPh,4,hadamard vs random_forest,10,10,0.0,0.000181,17.014996,True
7,AstroPh,8,hadamard vs random_forest,10,10,0.0,0.000183,14.657226,True
8,CITESEER,1,hadamard vs random_forest,10,10,0.0,0.000179,3.002180,True
9,CITESEER,2,hadamard vs random_forest,10,10,0.0,0.000181,5.704854,True
10,CITESEER,4,hadamard vs random_forest,10,10,0.0,0.000181,6.838945,True
11,CITESEER,8,hadamard vs random_forest,10,10,0.0,0.000182,5.505369,True
12,Cit-HepPh,1,hadamard vs random_forest,10,10,0.0,0.000182,4.208397,True
13,Cit-HepPh,2,hadamard vs random_forest,10,10,0.0,0.000182,13.679530,True
14,Cit-HepPh,4,hadamard vs random_forest,10,10,0.0,0.000177,14.962068,True
15,Cit-HepPh,8,hadamard vs random_forest,10,10,0.0,0.000181,7.485247,True

Metric: MRR

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,hadamard vs random_forest,10,10,0.0,0.000183,18.137347,True
1,AS-Oregon,2,hadamard vs random_forest,10,10,0.0,0.000183,27.225061,True
2,AS-Oregon,4,hadamard vs random_forest,10,10,0.0,0.000183,26.024915,True
3,AS-Oregon,8,hadamard vs random_forest,10,10,0.0,0.000183,35.080354,True
4,AstroPh,1,hadamard vs random_forest,10,10,0.0,0.000183,9.947265,True
5,AstroPh,2,hadamard vs random_forest,10,10,0.0,0.000183,13.381325,True
6,AstroPh,4,hadamard vs random_forest,10,10,0.0,0.000183,22.669070,True
7,AstroPh,8,hadamard vs random_forest,10,10,0.0,0.000183,17.185882,True
8,CITESEER,1,hadamard vs random_forest,10,10,0.0,0.000183,4.182538,True
9,CITESEER,2,hadamard vs random_forest,10,10,0.0,0.000182,7.230132,True
10,CITESEER,4,hadamard vs random_forest,10,10,0.0,0.000183,7.745140,True
11,CITESEER,8,hadamard vs random_forest,10,10,0.0,0.000183,6.661863,True
12,Cit-HepPh,1,hadamard vs random_forest,10,10,0.0,0.000183,7.748959,True
13,Cit-HepPh,2,hadamard vs random_forest,10,10,0.0,0.000183,15.118824,True
14,Cit-HepPh,4,hadamard vs random_forest,10,10,0.0,0.000183,18.214839,True
15,Cit-HepPh,8,hadamard vs random_forest,10,10,0.0,0.000183,9.674118,True

Metric: F1

,dataset,partitions,comparison,n1,n2,U,p-value,Cohen's d,significant
0,AS-Oregon,1,hadamard vs random_forest,10,10,66.0,0.241322,-0.439160,False
1,AS-Oregon,2,hadamard vs random_forest,10,10,52.0,0.909722,-0.081671,False
2,AS-Oregon,4,hadamard vs random_forest,10,10,59.0,0.520523,-0.208845,False
3,AS-Oregon,8,hadamard vs random_forest,10,10,61.0,0.427355,-0.044576,False
4,AstroPh,1,hadamard vs random_forest,10,10,56.0,0.677585,-0.194592,False
5,AstroPh,2,hadamard vs random_forest,10,10,46.0,0.791337,0.082018,False
6,AstroPh,4,hadamard vs random_forest,10,10,51.0,0.969850,0.103902,False
7,AstroPh,8,hadamard vs random_forest,10,10,55.0,0.733730,-0.226599,False
8,CITESEER,1,hadamard vs random_forest,10,10,53.0,0.850107,-0.072578,False
9,CITESEER,2,hadamard vs random_forest,10,10,61.0,0.427355,-0.297989,False
10,CITESEER,4,hadamard vs random_forest,10,10,59.0,0.520523,-0.280637,False
11,CITESEER,8,hadamard vs random_forest,10,10,49.0,0.969850,0.237262,False
12,Cit-HepPh,1,hadamard vs random_forest,10,10,73.0,0.088973,-0.857272,False
13,Cit-HepPh,2,hadamard vs random_forest,10,10,22.0,0.037635,1.077516,True
14,Cit-HepPh,4,hadamard vs random_forest,10,10,49.0,0.969850,-0.058216,False
15,Cit-HepPh,8,hadamard vs random_forest,10,10,60.0,0.472676,-0.159540,False